name: End to End Testing

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - 'v*'
  pull_request: {}
  workflow_dispatch: {}

env:
  # UP_ORG: ${{ secrets.UP_ORG }}
  # UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_DEV_ORG: ${{ secrets.UP_DEV_ORG }}
  UP_DEV_API_TOKEN: ${{ secrets.UP_DEV_API_TOKEN }}
  UP_DEV_ROBOT_ID: ${{ secrets.UP_DEV_ROBOT_ID }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [go, go-templating, kcl, python]
        test-language: [kcl, python]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          path: ./template

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '>=1.24.0'
          cache: false

      # during uxp2 development we need upbound-dev login here
      - name: Install and login with up
        if: env.UP_DEV_API_TOKEN != '' && env.UP_DEV_ORG != ''
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_DEV_API_TOKEN }}
          organization: ${{ secrets.UP_DEV_ORG }}

      # during uxp2 development we need upbound-dev login here
      - name: Login to xpkg with robot
        if: env.UP_DEV_API_TOKEN != '' && env.UP_DEV_ORG != ''
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ env.UP_DEV_ROBOT_ID }}
          password: ${{ env.UP_DEV_API_TOKEN }}

      - name: Initialize project
        run: up project init -t ./template generated-project --language ${{ matrix.language }} --test-language ${{ matrix.test-language }}

      - name: Build project
        run: cd generated-project && up project build

      - name: Run e2e tests
        run: cd generated-project && up test run tests/* --e2e --local --skip-control-plane-cleanup

      - name: Install kind CLI
        if: failure()
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install supportbundle CLI
        if: failure()
        run: |
          curl -Lo ./support-bundle https://github.com/replicatedhq/troubleshoot/releases/latest/download/support-bundle_linux_amd64.tar.gz
          tar -xzf ./support-bundle
          chmod +x ./support-bundle
          sudo mv ./support-bundle /usr/local/bin/support-bundle

      - name: Collect diagnostic information
        if: failure()
        run: |
          kind get clusters
          FIRST_CLUSTER=$(kind get clusters | head -n 1)
          if [ -n "$FIRST_CLUSTER" ]; then
            kind export kubeconfig --name "$FIRST_CLUSTER"
            support-bundle --kubeconfig ~/.kube/config --output support-bundle.tar.gz ./template/.github/supportbundle.yaml
          else
            echo "No kind clusters found"
            touch support-bundle.tar.gz
          fi

      - name: Upload support bundle
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: support-bundle-${{ matrix.language }}-${{ matrix.test-language }}
          path: support-bundle.tar.gz
          retention-days: 1
